# Generated by Django 3.2.7 on 2021-11-03 23:13

import cerberus.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.JSONField(validators=[cerberus.validator.BareValidator.validate]),
        ),
    ]
