# Generated by Django 3.2.7 on 2021-11-03 23:28

import cerberus.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='colours',
            new_name='primary_colours',
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.JSONField(validators=[cerberus.validator.BareValidator.validate]),
        ),
    ]
