# Generated by Django 3.2.7 on 2021-11-03 23:46

from django.db import migrations, models
import products.validator


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211103_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.JSONField(validators=[products.validator.validate_quantity]),
        ),
    ]
