# Generated by Django 3.2.7 on 2021-11-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211104_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
