# Generated by Django 3.2.7 on 2021-11-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_options',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
