# Generated by Django 3.2.7 on 2021-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20211106_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_options',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
